### ISSUE TITLE
Should wrollup embed its own specific version of rollup?

### ISSUE THREAD

**Issue by talmobi** [talmobi/wrollup#5]
@consense Do you think wrollup should include its own version of rollup?

I'm thinking that it shouldn't because I usually build with rollup directly and use wrollup for watching/development, this way wrollup would use the same version of rollup I'm using directly to build with.

Thoughts?

**Comment by consense** [comment]
Yes, would agree with your reasoning. 
Have to admit though that I switched to webpack2 for the time being as recompilation of typescript files while watching is noticeably faster there. Guess it's a matter of the respective typescript plugins working differently.
