### ISSUE TITLE
"process.chdir" messes up local script

### ISSUE THREAD

**Issue by ArthurClemens** [talmobi/wrollup#6]
In my rollup script I use 
```
const pkg = JSON.parse(fs.readFileSync("./package.json"));
```
but this does not work when wrollup is calling the script, because `process.chdir` in wrollup's index.js changes the working directory.

Is it actually needed? Commenting out that line seems to work fine...

**Comment by talmobi** [comment]
You're right! It doesn't seem to have any kind of desired effect. Patched this and made wrollup throw an error explicitly if it can't find a `rollup.config.js` file on 0.1.21.

> when rollup is calling the script

Could you clarify your meaning? Do you mean you're calling a script inside the `rollup.config.js` file that wrollup/rollup parses?

Does the new version (`npm install --save-dev wrollup@latest`) fix your issue? Basically just used your solution.

**Comment by ArthurClemens** [comment]
This solves the issue, thanks.
